### ISSUE TITLE
More Info On Why This Was Abandoned? (from a C++ on embedded systems perspective)

### ISSUE THREAD

**Issue by gbmhunter** [yuriykulikov/Abandoned-Event-driven_Framework_for_Embedded_Systems#7]
@yuriykulikov after revisiting this repo to see it has been abandoned, I am interested to know more details on why C++ did not end up being suitable. I have used C++ on embedded systems before and are looking to do so again, but are looking for valuable input into the disadvantages/risks of doing so.

**Comment by yuriykulikov** [comment]
Hi,
I have experienced some issues with compilers for avr chips and in the end
I have ended up programming simple OOP in C. I have barely used any c++
features anyway.  It was 5 years ago and perhaps things have changed in the
compiler department. Besides, currently nobody cares about avr because
there are lots of cheap and great arm chips out there:-) if you feel like
it, you should totally give it a try.
Br, Yuriy

Geoffrey Hunter <notifications@github.com> schrieb am Mi., 19. Apr. 2017,
22:44:

**Comment by gbmhunter** [comment]
O.K. thanks for the feedback. Yes ARM seems to be everywhere these days :-) Good to hear that the abandonment was not because of some major, generic issue w.r.t running C++ on an embedded system.
